#!/usr/bin/env bash
# Copyright (c) 2018 Denis Trofimov (den.a.trofimov@yandex.ru)
# Distributed under the MIT License.
# See accompanying file LICENSE.md or copy at http://opensource.org/licenses/MIT

set -ev

#ls submodules/folly

#cmake -E make_directory submodules/folly

# cd submodules/build-g3log
#pushd submodules/folly

#cmake -E chdir submodules/folly git submodule update --init --recursive

# store rev before patches
prev_rev_parse=$(cmake -E chdir submodules/folly git rev-parse HEAD)

# patch generated by
# cmake -E chdir submodules/folly git diff --cached > ../../patches/folly/0001-clang-cling-support.patch

# fix for https://github.com/facebook/folly/issues/976
cmake -E chdir submodules/folly git apply ../../patches/folly/0001-clang-cling-support.patch

cmake -E chdir submodules/folly cmake -E make_directory _build1

# cd _build1
#pushd _build1

#cmake -E chdir submodules/folly ls -artl

#cmake -E chdir submodules/folly ls -artl CMake

# CMAKE_POSITION_INDEPENDENT_CODE for -fPIC
cmake -E chdir submodules/folly cmake -E chdir _build1 cmake -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON ..

cmake -E chdir submodules/folly cmake -E chdir _build1 make -j $(nproc)

cmake -E chdir submodules/folly cmake -E chdir _build1 make install # with either sudo or DESTDIR as necessary

# Revert patches after install:
# NOTE: git reset --hard '@{u}' deletes all your local changes on
# the current branch, including commits.
# git reset --hard '@{u}'
# NOTE: Deletes the most recent commit:
# git reset --hard HEAD~1
# NOTE: reset --hard to set the current branch HEAD to the commit you want.
cmake -E chdir submodules/folly git reset --hard $prev_rev_parse
# NOTE: git clean -f -d to remove all the untracked
# files in your working directory
cmake -E chdir submodules/folly git clean -f -d

# Clean after install:

# cd ..
#pushd ..

cmake -E chdir submodules/folly cmake -E remove_directory _build1
